### ISSUE TITLE
Hot reload issue

### ISSUE THREAD

**Issue by gildas-lormeau** [zetapush/zetapush#56]
Sometimes, the worker code won't deploy. To reproduce the issue, create the sample app, change the string returned by the `hello` method several times. I was able to reproduce the issue after applying 2 changes in the worker code.

The following error is displayed in the console. Restarting the worker seems to solve the issue.

```
WorkerInstance::error TypeError: Cannot read property 'hello' of undefined
    at result (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/worker/lib/utils/worker-instance.js:57:79)
    at Promise (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/worker/lib/utils/async.js:21:22)
    at new Promise (<anonymous>)
    at timeoutify (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/worker/lib/utils/async.js:15:46)
    at WorkerInstance.dispatch (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/worker/lib/utils/worker-instance.js:57:50)
    at dispatch (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/worker/lib/client/worker.js:75:43)
    at _notify (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/cometd/lib/CometD.js:353:47)
    at _notifyListeners (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/cometd/lib/CometD.js:374:9)
    at _messageResponse (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/cometd/lib/CometD.js:1010:17)
    at _receive (/mnt/c/Users/Gildas/Dev/project-zetapush/test-app/node_modules/@zetapush/cometd/lib/CometD.js:1065:17)
```

On client-side the following error may be displayed.
```
helper.js:14 Uncaught (in promise) ApiError
    at onError (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:7183:28)
    at _notify (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:3559:39)
    at _notifyListeners (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:3582:9)
    at _messageResponse (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:4341:13)
    at _receive (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:4410:13)
    at CometD._handleMessages (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:4430:11)
    at F.onSuccess (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:3686:31)
    at F.WebSocketTransport._self._notifySuccess (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:6072:12)
    at F.WebSocketTransport._self.onMessage (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:6195:14)
    at WebSocket.onmessage (https://unpkg.com/@zetapush/core@0.27.14/dist/zetapush.js:6013:16)
```

**Comment by gildas-lormeau** [comment]
It looks like a `npm run deploy` may be also needed to recover from this issue sometimes.

**Comment by ghoullier** [comment]
This issue seems to be related to hot module replacement. 
We plan to work on a more stable and flaggable implementation.

**Comment by ghoullier** [comment]
The fixing [pull-request](https://github.com/sidorares/hot-module-replacement/pull/3) was merged to the repository of hot_module_replacement, we are waiting for the npm publication.
